# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mkrel < Formula
  desc "Release management tool with Git Flow and CalVer/SemVer support"
  homepage "https://github.com/kloudlabs-io/mkrel"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kloudlabs-io/mkrel/releases/download/v0.4.0/mkrel_0.4.0_darwin_amd64.tar.gz"
      sha256 "dcbe3f0ef0814383a44b535896846d4fafafc683ba60bf0e5df893827e00855b"

      def install
        bin.install "mkrel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kloudlabs-io/mkrel/releases/download/v0.4.0/mkrel_0.4.0_darwin_arm64.tar.gz"
      sha256 "678c6b6d304dffa60a3b44b002389f689726568fe1e12edafb34b29df2d978ed"

      def install
        bin.install "mkrel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kloudlabs-io/mkrel/releases/download/v0.4.0/mkrel_0.4.0_linux_amd64.tar.gz"
      sha256 "49437617835ac5ffac9ebf99c09c6287f35c53e3a7547d959a2e60a29b094445"
      def install
        bin.install "mkrel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kloudlabs-io/mkrel/releases/download/v0.4.0/mkrel_0.4.0_linux_arm64.tar.gz"
      sha256 "5abae13a6f988be27a1678332cdee8fbdadcd8a149b22e54e81bfff80dc77596"
      def install
        bin.install "mkrel"
      end
    end
  end
end
