# This file was generated by GoReleaser. DO NOT EDIT.
cask "mkrel" do
  name "mkrel"
  desc "Release management tool with Git Flow and CalVer/SemVer support"
  homepage "https://github.com/kloudlabs-io/mkrel"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mkrel"

  on_macos do
    on_intel do
      url "https://github.com/kloudlabs-io/mkrel/releases/download/v#{version}/mkrel_#{version}_darwin_amd64.tar.gz"
      sha256 "7581aa252574edc25b2f221b272ceebf19711c7b21c8c1f795e94e418d274825"
    end
    on_arm do
      url "https://github.com/kloudlabs-io/mkrel/releases/download/v#{version}/mkrel_#{version}_darwin_arm64.tar.gz"
      sha256 "8903af0e0511bd97b8a8e49a6dc2121d77dfd23fd9176419faede3a438fd4e89"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kloudlabs-io/mkrel/releases/download/v#{version}/mkrel_#{version}_linux_amd64.tar.gz"
      sha256 "67d9ec502f63614fcde0918486ae13e5abf06f0bfd5816b90bc7f778bc2abffe"
    end
    on_arm do
      url "https://github.com/kloudlabs-io/mkrel/releases/download/v#{version}/mkrel_#{version}_linux_arm64.tar.gz"
      sha256 "23c47a59d0e17490945a2233a033c9e8874eacda123d0ba2316150ae1f64599b"
    end
  end

  # No zap stanza required
end
